spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.bilibili.com
          predicates:
            - Query=url, baidu
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url, qq
